baseURL = 'https://almstueberlmusi.at/'
languageCode = 'de-at'
title = 'AlmstÃ¼berl Musi'
theme = "bienensteff"

[params.main]
  img = "avatar.jpg"
  icon = "avatar.jpg"

[menus]
[[menus.main]]
name = "Booking"
pageRef = "/booking"
weight = 10

[[menus.main]]
name = "Veranstaltungen"
pageRef = "/veranstaltungen"
weight = 20

[[menus.main]]
name = "Galerie"
pageRef = "/galerie"
weight = 30

[[menus.main]]
name = "Ãœber uns"
pageRef = "/Ã¼ber-uns"
weight = 40

[[menus.footer]]
name = 'ðŸ”— Instagram'
URL = 'https://www.instagram.com/almstueberl_musi'
weight = 10

[[menus.footer]]
name = 'Impressum'
pageRef = '/impressum'
weight = 20


[markup.goldmark.renderer]
  unsafe = true

[imaging]
  quality = 97
  resampleFilter = "Lanczos"
